### ISSUE TITLE
Why drop support for net 4.5.2?

### ISSUE THREAD

**Issue by Jericho** [hey-red/MimeTypesMap#5]
As documented [here](https://github.com/Microsoft/dotnet/blob/master/releases/README.md), `net452` is still supported. I agree that your library shouldn't have to support `net40` and `net45` but I think you should still support `net452` (in addition to `netstandard1.0` and `netstandard2.0`).

**Comment by hey-red** [comment]
But you can use netstandard1.0 lib with your .NET 4.5.2 application. According this table https://github.com/dotnet/standard/blob/master/docs/versions.md
Maybe I'm wrong?

**Comment by Jericho** [comment]
That might be technically true, but I also know that there are some possible compatibility issues consuming .net standard libraries from .net framework projects. Such as:

> While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

It's not 100% clear to me if the same compatibility issues are present when loading a `netstandard1.0` from a `net452` project. Therefore I always make sure my libraries multi-targeting `net452`, `netstandard1.0` and `netstandard2.0`, I want to avoid these kind of issues that are probably difficult to investigate and diagnose. 

That's why, in my opinion, you should target net452 (which the is oldest full framework still supported by Microsoft) in addition to netstandard1 and netstandard2.

Does it make sense?

**Comment by hey-red** [comment]
Okay. It's no problem to add additional target.

**Comment by Jericho** [comment]
Excellent. Thank you.

**Comment by gitfool** [comment]
Support for .NET Framework is a mess. If you need to cover _all_ bases then it seems the guidance is to use:
```
<TargetFrameworks>netstandard1.3;netstandard2.0;net45;net461;net472</TargetFrameworks>
```
😞 

https://twitter.com/andrewlocknet/status/1121049785698586624

**Comment by Jericho** [comment]
> netstandard1.3 for max support if you want < 2.0

I agree with this. Although we are only a few months away from [netcore 1.0 and 1.1 reaching end-of-life](https://blogs.msdn.microsoft.com/dotnet/2019/02/19/net-core-1-0-and-1-1-will-reach-end-of-life-on-june-27-2019/) so supporting netstandard1.x is not as important as it used to be.

> net45 for < net461 (if you need it)

I prefer to target net452 because Microsoft [stopped supporting net45 and net451](https://devblogs.microsoft.com/dotnet/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) in January 2016.

> netstandard2.0 to avoid huge dependency graph of netstandard1.x

I agree

> net461 to avoid crap netstandard2.0 implementation issues

As I understand it, net461 is supposed to implement netstandard2.0 but I have heard there are issues and therefore it's safer for libraries to also target net461.

> net472 to override net461 hack!

This is news to me. What hack are we talking about?

**Comment by gitfool** [comment]
@Jericho not sure exactly but it's alluded to here:

https://twitter.com/terrajobst/status/1031999730320986112
